version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rightfit-postgres
    environment:
      POSTGRES_USER: rightfit_user
      POSTGRES_PASSWORD: rightfit_dev_password
      POSTGRES_DB: rightfit_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rightfit_user -d rightfit_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
