#!/bin/bash

# RightFit Services - Environment Synchronization Script
# This script ensures all individual app .env files have the correct API keys and configuration
# It uses the root .env and .env.separated files to populate each app's .env file

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

log_info "🔧 RightFit Services - Environment Synchronization"
log_info "Project Root: $PROJECT_ROOT"

# Source the main environment files
log_info "📄 Loading environment files..."
if [ -f "$PROJECT_ROOT/.env" ]; then
    source "$PROJECT_ROOT/.env"
    log_success "✅ Loaded main .env file"
else
    log_error "❌ Main .env file not found at $PROJECT_ROOT/.env"
    exit 1
fi

if [ -f "$PROJECT_ROOT/.env.separated" ]; then
    source "$PROJECT_ROOT/.env.separated"
    log_success "✅ Loaded .env.separated file"
else
    log_warning "⚠️  .env.separated file not found at $PROJECT_ROOT/.env.separated"
fi

# Function to create/update .env file for an app
update_app_env() {
    local app_name=$1
    local app_path="$PROJECT_ROOT/apps/$app_name"
    local env_file="$app_path/.env"
    local app_port=$2
    local app_prefix=$3

    log_info "📱 Updating $app_name environment..."

    if [ ! -d "$app_path" ]; then
        log_warning "⚠️  App directory not found: $app_path"
        return
    fi

    # Create the .env file content
    cat > "$env_file" << EOF
# =====================================================
# RightFit Services - $app_name Environment Configuration
# =====================================================
# Auto-generated by sync-env.sh - DO NOT EDIT MANUALLY
# Generated on: $(date)
#
# This file contains all environment variables needed for the $app_name app
# It combines settings from the main .env and .env.separated files

# -----------------------------------------------------
# Core Application Settings
# -----------------------------------------------------
NODE_ENV=$NODE_ENV
VITE_APP_NAME="RightFit $app_prefix"
VITE_API_BASE_URL=\${CLEANING_API_URL:-http://localhost:3001}

# Development Server Configuration
VITE_PORT=$app_port

# API URLs (from separated services configuration)
\${CLEANING_API_URL:+CLEANING_API_URL=}
\${MAINTENANCE_API_URL:+MAINTENANCE_API_URL=}
\${SHARED_AUTH_API_URL:+SHARED_AUTH_API_URL=}
\${ORIGINAL_DATABASE_URL:+ORIGINAL_DATABASE_URL=}

# Frontend URLs (for CORS and API calls)
\${CLEANING_WEB_URL:+CLEANING_WEB_URL=}
\${MAINTENANCE_WEB_URL:+MAINTENANCE_WEB_URL}
\${CUSTOMER_WEB_URL:+CUSTOMER_WEB_URL}
\${LANDLORD_WEB_URL:+LANDLORD_WEB_URL}

# -----------------------------------------------------
# Authentication Configuration
# -----------------------------------------------------
JWT_SECRET="$JWT_SECRET"
JWT_REFRESH_SECRET="$JWT_REFRESH_SECRET"
JWT_ACCESS_EXPIRY="$JWT_ACCESS_EXPIRY"
JWT_REFRESH_EXPIRY="$JWT_REFRESH_EXPIRY"

# -----------------------------------------------------
# Database Configuration
# -----------------------------------------------------
DATABASE_URL="$DATABASE_URL"
\${SHARED_AUTH_DATABASE_URL:+SHARED_AUTH_DATABASE_URL=}
\${CLEANING_DATABASE_URL:+CLEANING_DATABASE_URL=}
\${MAINTENANCE_DATABASE_URL:+MAINTENANCE_DATABASE_URL}

# -----------------------------------------------------
# External Service Configuration
# -----------------------------------------------------

# Email Services
SENDGRID_API_KEY="$SENDGRID_API_KEY"
SENDGRID_FROM_EMAIL="$SENDGRID_FROM_EMAIL"
RESEND_API_KEY="$RESEND_API_KEY"
RESEND_FROM_EMAIL="$RESEND_FROM_EMAIL"

# SMS Services
TWILIO_ACCOUNT_SID="$TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN="$TWILIO_AUTH_TOKEN"
TWILIO_PHONE_NUMBER="$TWILIO_PHONE_NUMBER"

# GPS Navigation and Weather APIs
WEATHER_API_KEY="$WEATHER_API_KEY"
TOMTOM_API_KEY="$TOMTOM_API_KEY"
WHAT3WORDS_API_KEY="$WHAT3WORDS_API_KEY"

# Map Services
VITE_MAPBOX_TOKEN="$VITE_MAPBOX_TOKEN"
VITE_MAPBOX_SECRET_KEY="$VITE_MAPBOX_SECRET_KEY"

# -----------------------------------------------------
# Feature Flags and Configuration
# -----------------------------------------------------

# Service Mode (unified, separated, migration)
\${SERVICE_MODE:+SERVICE_MODE=$SERVICE_MODE}
\${API_VERSION:+API_VERSION=$API_VERSION}
\${ENABLE_SEPARATED_SERVICES:+ENABLE_SEPARATED_SERVICES=$ENABLE_SEPARATED_SERVICES}
\${DISABLE_UNIFIED_DATABASE:+DISABLE_UNIFIED_DATABASE=$DISABLE_UNIFIED_DATABASE}

# Rate Limiting
RATE_LIMIT_WINDOW_MS="$RATE_LIMIT_WINDOW_MS"
RATE_LIMIT_MAX_REQUESTS="$RATE_LIMIT_MAX_REQUESTS"

# Development Settings
\${API_LOG_REQUESTS:+API_LOG_REQUESTS=$API_LOG_REQUESTS}
\${DB_LOG_QUERIES:+DB_LOG_QUERIES=$DB_LOG_SLOW_QUERIES}
\${DB_SLOW_QUERY_THRESHOLD:+DB_SLOW_QUERY_THRESHOLD=$DB_SLOW_QUERY_THRESHOLD}
\${MIGRATION_DEBUG:+MIGRATION_DEBUG=$MIGRATION_DEBUG}
\${MIGRATION_VERBOSE:+MIGRATION_VERBOSE=$MIGRATION_VERBOSE}

# CORS Configuration
ALLOWED_ORIGINS="$ALLOWED_ORIGINS"

# Health Check
ENABLE_METRICS_ENDPOINT="${ENABLE_METRICS_ENDPOINT:-true}"
METRICS_PORT="${METRICS_PORT:-9090}"

# -----------------------------------------------------
# App-Specific Configuration
# ------------------------------------------------====

EOF

    # Add app-specific configurations
    case $app_name in
        "web-cleaning")
            cat >> "$env_file" << 'EOF'

# Cleaning Service Specific
VITE_SERVICE_TYPE="cleaning"
VITE_API_URL=${CLEANING_API_URL:-http://localhost:3001}
VITE_WORKER_APP_URL="http://localhost:5178"

# Feature Flags
VITE_ENABLE_GPS_NAVIGATION=true
VITE_ENABLE_JOB_SCHEDULING=true
VITE_ENABLE_PHOTO_UPLOAD=true
VITE_ENABLE_CERTIFICATE_MANAGEMENT=true
EOF
            ;;
        "web-maintenance")
            cat >> "$env_file" << 'EOF'

# Maintenance Service Specific
VITE_SERVICE_TYPE="maintenance"
VITE_API_URL=${MAINTENANCE_API_URL:-http://localhost:3001}
VITE_WORKER_APP_URL="http://localhost:5178"

# Feature Flags
VITE_ENABLE_GPS_NAVIGATION=true
VITE_ENABLE_WORK_ORDERS=true
VITE_ENABLE_INVENTORY_MANAGEMENT=true
VITE_ENABLE_TIME_SHEETS=true
VITE_ENABLE_ISSUE_REPORTING=true
EOF
            ;;
        "web-customer")
            cat >> "$env_file" << 'EOF'

# Customer Service Specific
VITE_SERVICE_TYPE="customer"
VITE_API_URL=${CLEANING_API_URL:-http://localhost:3001}
VITE_CUSTOMER_PORTAL_URL="http://localhost:5176"

# Feature Flags
VITE_ENABLE_PROPERTY_MANAGEMENT=true
VITE_ENABLE_SERVICE_BOOKING=true
VITE_ENABLE_JOB_TRACKING=true
VITE_ENABLE_PAYMENT_PROCESSING=true
VITE_ENABLE_REVIEWS_AND_RATINGS=true
EOF
            ;;
        "web-landlord")
            cat >> "$env_file" << 'EOF'

# Landlord Service Specific
VITE_SERVICE_TYPE="landlord"
VITE_API_URL=${MAINTENANCE_API_URL:-http://localhost:3001}
VITE_LANDLORD_PORTAL_URL="http://localhost:5173"

# Feature Flags
VITE_ENABLE_PROPERTY_MANAGEMENT=true
VITE_ENABLE_TENANT_MANAGEMENT=true
VITE_ENABLE_MAINTENANCE_REQUESTS=true
VITE_ENABLE_FINANCIAL_REPORTING=true
VITE_ENABLE_DOCUMENT_STORAGE=true
EOF
            ;;
        "guest-tablet")
            cat >> "$env_file" << 'EOF'

# Guest Tablet Service Specific
VITE_SERVICE_TYPE="guest"
VITE_API_URL=${CLEANING_API_URL:-http://localhost:3001}

# Feature Flags
VITE_ENABLE_ISSUE_REPORTING=true
VITE_ENABLE_PHOTO_UPLOAD=true
VITE_ENABLE_GUEST_PORTAL=true
VITE_ENABLE_OFFLINE_MODE=true
EOF
            ;;
        "web-worker")
            cat >> "$env_file" << 'EOF'

# Worker Mobile App Configuration
VITE_SERVICE_TYPE="worker"
VITE_API_URL=${CLEANING_API_URL:-http://localhost:3001}
VITE_WORKER_APP_URL="http://localhost:5178"

# Mobile App Specific
VITE_ENABLE_GPS_TRACKING=true
VITE_ENABLE_OFFLINE_MODE=true
VITE_ENABLE_PUSH_NOTIFICATIONS=true
VITE_ENABLE_PHOTO_CAPTURE=true
VITE_ENABLE_JOB_NAVIGATION=true
VITE_ENABLE_TIME_SHEET_TRACKING=true
EOF
            ;;
    esac

    # The header is already included in the cat > EOF block above, so no need to add it again

    log_success "✅ Updated $app_name .env file"
}

# Update API environment
log_info "🔧 Updating API environment..."
update_app_env "api" "3001" "API"

# Update web applications
log_info "🖼️  Updating web applications..."
update_app_env "web-cleaning" "5174" "Cleaning"
update_app_env "web-maintenance" "5175" "Maintenance"
update_app_env "web-customer" "5176" "Customer"
update_app_env "web-landlord" "5173" "Landlord"

# Update guest applications
log_info "📱 Updating guest applications..."
update_app_env "guest-tablet" "8080" "Guest Tablet"

# Update worker applications
log_info "👷 Updating worker applications..."
update_app_env "web-worker" "5177" "Worker"

# Create a summary of what was updated
log_success "🎉 Environment synchronization completed!"
log_info ""
log_info "📋 Updated Files:"
log_info "  - apps/api/.env"
log_info "  - apps/web-cleaning/.env"
log_info "  - apps/web-maintenance/.env"
log_info "  - apps/web-customer/.env"
log_info "  - apps/web-landlord/.env"
log_info "  - apps/guest-tablet/.env"
log_info "  - apps/web-worker/.env"
log_info ""
log_info "🔧 All environment files now contain:"
log_info "  ✓ JWT secrets for authentication"
log_info "  ✓ Database connections"
log_info "  ✓ API service URLs"
log_info "  ✓ Email service configuration (SendGrid, Resend)"
log_info "  ✓ SMS service configuration (Twilio)"
log_info "  ✓ GPS and navigation APIs (Weather, TomTom, what3words)"
log_info "  ✓ Mapbox configuration"
log_info "  ✓ CORS configuration"
log_info "  ✓ Feature flags and service modes"
log_info ""
log_info "💡 To update files in the future, run:"
log_info "  $ ./sync-env.sh"
log_info ""
log_info "🚀 Applications are now ready to run with proper configuration!"