import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'properties',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'address_line1', type: 'string', isOptional: true },
        { name: 'address_line2', type: 'string', isOptional: true },
        { name: 'city', type: 'string', isOptional: true },
        { name: 'state', type: 'string', isOptional: true },
        { name: 'zip_code', type: 'string', isOptional: true },
        { name: 'type', type: 'string', isOptional: true },
        { name: 'bedrooms', type: 'number', isOptional: true },
        { name: 'bathrooms', type: 'number', isOptional: true },
        { name: 'square_footage', type: 'number', isOptional: true },
        { name: 'rent_amount', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'work_orders',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'property_id', type: 'string', isIndexed: true },
        { name: 'contractor_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'estimated_cost', type: 'number', isOptional: true },
        { name: 'actual_cost', type: 'number', isOptional: true },
        { name: 'due_date', type: 'number', isOptional: true },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'contractors',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'company_name', type: 'string', isOptional: true },
        { name: 'trade', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'photos',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'work_order_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'property_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'local_uri', type: 'string' },
        { name: 's3_url', type: 'string', isOptional: true },
        { name: 'thumbnail_url', type: 'string', isOptional: true },
        { name: 'label', type: 'string', isOptional: true },
        { name: 'caption', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'entity_type', type: 'string', isIndexed: true },
        { name: 'entity_id', type: 'string', isIndexed: true },
        { name: 'action', type: 'string' }, // 'create', 'update', 'delete'
        { name: 'payload', type: 'string' }, // JSON string
        { name: 'attempts', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'property_tenants',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'property_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'move_in_date', type: 'number' },
        { name: 'lease_expiry_date', type: 'number', isOptional: true },
        { name: 'rent_amount', type: 'number' },
        { name: 'rent_frequency', type: 'string' },
        { name: 'rent_due_day', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rent_payments',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'property_tenant_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'payment_date', type: 'number' },
        { name: 'expected_date', type: 'number', isOptional: true },
        { name: 'payment_method', type: 'string', isOptional: true },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'financial_transactions',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'property_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'amount', type: 'number' },
        { name: 'date', type: 'number', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'receipt_url', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'property_budgets',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'property_id', type: 'string', isIndexed: true },
        { name: 'monthly_budget', type: 'number' },
        { name: 'alert_threshold', type: 'number' },
        { name: 'synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})
